- name: task level variables
  hosts: local
  connection: local #if we give connection as local then no need to give username & password
  vars:  
    COURSE: "Devsecops with AWS"  # Declaring variables
    DURATION: "140HRS"
    TRAINER: "Sivakumar"
  tasks:
  - name: print variables
    vars:
      COURSE: Ansible     #task level variables will override play level variables, values may change or maynot change.
    ansible.builtin.debug:
      msg: "Course is: {{ COURSE }}, Trainer is: {{ TRAINER }}" #reffering variables 

