- name: demo on loops
  hosts: local
  connection: local
  tasks:
  - name: print names
    ansible.builtin.debug:
      msg: "Hello {{ item }}" # item is reserved keyword in ansible
    loop: 
    - Raju
    - Soumya
    - Tanshinisai

# Ansible loop list of variables and take it into item in every iteration one by one.