- name: demo on filters
  hosts: local
  connection: local
  vars:
    topics: linux,shell,ansible,terraform  # string datatype
    course: "Devops with Ansible"
    myIp: "192.23.89.123"
    tagsList: # map/dictionary
      name: ansible
      project: roboshop
      component: catalogue
    tagsMap: [    # list
        {
            "key": "name",
            "value": "ansible"
        },
        {
            "key": "project",
            "value": "roboshop"
        },
        {
            "key": "component",
            "value": "catalogue"
        }
    ]  
  tasks:
  - name: greeting # using default variable
    ansible.builtin.debug:
      msg: "Hi Soumya, {{ GREETING | default ('Good Morning')}}" # if we forgot to define variable here ,it automatically print by the help of default value.

  - name: convert string to list # by using split ','
    ansible.builtin.debug:
      msg: "{{ topics | split(',') }}" # if we don't mention ',' it will take it as space.

  - name: convert map to list
    ansible.builtin.debug:
      msg: "{{ tagsList | dict2items }}"

  - name: convert list to map
    ansible.builtin.debug:
      msg: "{{ tagsMap | items2dict }}"    

  - name: read students yaml
    ansible.builtin.set_fact: # setting the variable dynamically
      student_yaml: "{{ lookup('file', 'students.yaml' )}}"

  # Ansible findout student.yaml from available list of playbooks, then that inside content will give it to from_yaml & store it in student_yaml.

  - name: convert YAML to JSON
    ansible.builtin.debug:
      msg: "{{ student_yaml | to_nice_json }}" # this is for human readable

  - name: convert to upper case
    ansible.builtin.debug:
      msg: "{{ course | upper }}"

  - name: convert to lower case
    ansible.builtin.debug:
      msg: "{{ course | lower }}"

  - name: check ipv4
    ansible.builtin.debug:
      msg: "{{ myIp | ansible.utils.ipv4 }}" # using this filter for finding mentioned ip address is proper ipv4 or not.